apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: mtest-policy
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
  readOnlyRootFilesystem: false
  hostNetwork: true
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:mtest
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["mtest-policy"]
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:mtest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:mtest
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:serviceaccounts
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
