apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: mtest
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        readOnlyRootFilesystem: false
  hostNetwork: true
