version: 2.1
commands:
  run-mtest:
    description: "multi-host test"
    parameters:
      runtime:
        type: string
      suite:
        type: string
      cluster:
        type: string
        default: "cke-cluster.yml"
    steps:
      - run:
          name: Store Service Account
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT > account.json
            gcloud auth activate-service-account --key-file=account.json
      - run:
          name: Watch cke logs
          command: |
            if [ -f .skip ]; then exit 0; fi
            ./bin/watch_service cke
          background: true
      - run:
          command: |
            ./bin/run-mtest.sh "<<parameters.runtime>>" "<<parameters.suite>>" "<<parameters.cluster>>"
          no_output_timeout: 20m
      - run:
          name: Set the instance lifetime
          command: |
            . ./bin/env
            $GCLOUD compute instances add-metadata ${INSTANCE_NAME} --zone ${ZONE} \
              --metadata shutdown-at=$(date -Iseconds -d+30minutes)
          when: on_fail
      - run:
          name: Notify to Slack
          command: |
            . ./bin/env
            curl -X POST -H 'Content-type: application/json' --data "{
              \"blocks\": [
                {
                  \"type\": \"section\",
                  \"text\": {
                    \"type\": \"mrkdwn\",
                    \"text\": \"Failed: ${CIRCLE_USERNAME}'s workflow (${CIRCLE_JOB}) in <https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/workflows/${CIRCLE_PROJECT_REPONAME}|${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}> (<https://circleci.com/gh/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/tree/${CIRCLE_BRANCH}|${CIRCLE_BRANCH}>)\n Do you extend the lifetime of ${INSTANCE_NAME}?\"
                  },
                  \"accessory\": {
                    \"type\": \"button\",
                    \"text\": {
                      \"type\": \"plain_text\",
                      \"text\": \"Extend\",
                      \"emoji\": true
                    },
                    \"value\": \"${INSTANCE_NAME}\"
                  }
                }
              ]
            }" $SLACK_WEBHOOK_URL
          when: on_fail
      - run:
          name: delete instance
          command: |
            . ./bin/env
            $GCLOUD compute instances delete ${INSTANCE_NAME} --zone ${ZONE}

jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.16-focal
      - image: quay.io/coreos/etcd:v3.3
    working_directory: /work
    steps:
      - checkout
      - run:
          name: Check static resources
          command: |
            cp ./static/resources.go /tmp/resources.go
            make static
            cmp /tmp/resources.go ./static/resources.go
      - run: make test GOBIN=/tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - cke
            - ckecli
  build-image:
    docker:
      - image: docker:stable
    steps:
      - run:
          name: Install tools
          command: |
            apk add --no-cache git
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy binaries
          command: |
            cp /tmp/workspace/cke docker
            cp /tmp/workspace/ckecli docker
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t quay.io/cybozu/cke:latest ./docker
      - run:
          name: Save image
          command: |
            mkdir -p /tmp/docker
            docker save quay.io/cybozu/cke:latest -o /tmp/docker/image
      - persist_to_workspace:
          root: /tmp/docker
          paths:
            - image
  push-image:
    docker:
      - image: docker:stable
    steps:
      - attach_workspace:
          at: /tmp/docker
      - setup_remote_docker
      - run: docker load -i /tmp/docker/image
      - run:
          name: Push docker image to Quay.io
          command: |
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            echo "pushing CKE image ..."
            TAG=$(echo $CIRCLE_TAG | cut -c 2-)
            docker tag quay.io/cybozu/cke:latest quay.io/cybozu/cke:$TAG
            docker push quay.io/cybozu/cke:$TAG
            if echo $TAG | grep -q -e - ; then
                echo ===== Skip pushing branch tags for pre-release $TAG =====
                exit 0
            fi
            BRANCH=$(echo $TAG | cut -d "." -f 1-2)
            docker tag quay.io/cybozu/cke:latest quay.io/cybozu/cke:$BRANCH
            docker push quay.io/cybozu/cke:$BRANCH
  mtest-containerd-functions:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run-mtest:
          runtime: remote
          suite: functions
  mtest-containerd-operators:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run-mtest:
          runtime: remote
          suite: operators
  mtest-containerd-robustness:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run-mtest:
          runtime: remote
          suite: robustness
  compose:
    machine:
      image: circleci/classic:edge
    working_directory: ~/work/example
    steps:
      - checkout:
          path: ~/work
      - run:
          name: Check image consistency
          command: |
            REV=$(awk '/const Version/ {print $4}' ../version.go | sed -E 's/^"(1.[[:digit:]]+).*/\1/')
            COMPOSE_REV=$(sed -nE 's,.*quay.io/cybozu/cke:(.*)$,\1,p' docker-compose.yml)
            if [ "$REV" != "$COMPOSE_REV" ]; then
                echo Update CKE branch tag in example/docker-compose.yml
            fi
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: wait for docker-compose up
          command: ./wait-up.sh
      - run:
          name: run test
          command: docker-compose run setup /opt/setup/test.sh
      - run:
          name: docker-compose down
          command: docker-compose down
  sonobuoy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT > account.json
            gcloud auth activate-service-account --key-file=account.json
      - run:
          name: Run Sonobuoy
          command: ./bin/run-sonobuoy.sh
          no_output_timeout: 240m
      - persist_to_workspace:
          root: /tmp
          paths:
            - sonobuoy.tar.gz
      - store_artifacts:
          path: /tmp/sonobuoy.tar.gz
      - run:
          name: Check failures
          command: |
            grep "failed tests: 0" /tmp/e2e-check.log
  github-release:
    docker:
      - image: quay.io/cybozu/golang:1.16-focal
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Prepare files
          command: |
            mkdir /tmp/upload
            cp /tmp/workspace/sonobuoy.tar.gz /tmp/upload
            tar xzf /tmp/workspace/sonobuoy.tar.gz -C /tmp/upload --strip-components=4 plugins/e2e/results/global/e2e.log plugins/e2e/results/global/junit_01.xml
            sed "s/vX\.Y\.Z/${CIRCLE_TAG}/" sonobuoy/README.md > /tmp/upload/README.md
            sed "s/vX\.Y\.Z/${CIRCLE_TAG}/" sonobuoy/PRODUCT.yaml > /tmp/upload/PRODUCT.yaml
            GOBIN=/tmp/upload go install ./pkg/cke ./pkg/ckecli
      - run:
          name: Release to GitHub
          command: |
            prrelease=
            if echo ${CIRCLE_TAG} | grep -q -e -; then
              prerelease="-prerelease"
            fi
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -n ${CIRCLE_TAG} $prerelease ${CIRCLE_TAG} /tmp/upload
  build-tools:
    docker:
    - image: quay.io/cybozu/golang:1.16-focal
    steps:
    - checkout
    - run:
        command: |
          cd tools
          make all
          tar czf /tmp/tools.tgz bin plugins/LICENSE plugins/bin
    - persist_to_workspace:
        root: /tmp
        paths: ["tools.tgz"]
  push-tools:
    docker:
    - image: docker:stable
    steps:
    - run:
        name: Install tools
        command: apk add --no-cache git
    - checkout
    - attach_workspace:
        at: /tmp/workspace
    - run: tar -C tools -xzf /tmp/workspace/tools.tgz
    - setup_remote_docker
    - run: 
        name: Push cke-tools image to Quay.io
        command: |
          docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
          TAG=quay.io/cybozu/cke-tools:$(echo $CIRCLE_TAG | cut -c 7-)
          docker build --no-cache -t $TAG tools
          docker push $TAG

workflows:
  version: 2
  main:
    jobs:
      - build
      - build-tools
      - build-image:
          requires:
            - build
      - mtest-containerd-functions
      - mtest-containerd-operators
      - mtest-containerd-robustness
      - compose
  conformance:
    jobs:
      - hold:
          type: approval
      - sonobuoy:
          requires:
            - hold
  release-image:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build-image:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - push-image:
          requires:
            - build-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
  release-github:
    jobs:
      - sonobuoy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - github-release:
          requires:
            - sonobuoy
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
  release-tools:
    jobs:
      - build-tools:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^tools-.*/
      - push-tools:
          requires:
          - build-tools
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^tools-.*/
