name: tutorial
nodes:
  - address: 192.168.1.101
    user: core
    control_plane: true
  - address: 192.168.1.102
    user: core
  - address: 192.168.1.103
    user: core
service_subnet: 10.34.56.0/24
pod_subnet: 10.1.0.0/16
dns_servers: ["8.8.8.8", "1.1.1.1"]
