version: '2'
services:
  cke:
    container_name: cke
    image: quay.io/cybozu/cke:1.13
    user: "${UID}:${GID}"
    volumes:
      - ./cke.config.yml:/etc/cke/config.yml
      - ./bin:/host
      - ./cke-entrypoint.sh:/entrypoint.sh
    depends_on:
      - etcd
      - vault
    restart: always
    entrypoint:
      - /entrypoint.sh
  setup:
    container_name: setup
    image: quay.io/cybozu/ubuntu-debug:18.04
    user: "${UID}:${GID}"
    volumes:
      - ./bin:/usr/local/bin
      - ./setup:/opt/setup
      - ./cke.config.yml:/etc/cke/config.yml
    depends_on:
      - vault
      - etcd
      - cke
    command: /opt/setup/setup.sh
  vault:
    container_name: vault
    image: quay.io/cybozu/vault:0.11
    user: "${UID}:${GID}"
    cap_add:
      - IPC_LOCK
    depends_on:
      - etcd
    volumes:
      - ./vault.hcl:/etc/vault/config.hcl
      - ./bin:/host
      - ./vault-entrypoint.sh:/entrypoint.sh
    ports:
      - "8200:8200"
      - "8201:8201"
    restart: always
    entrypoint:
      - /entrypoint.sh
  etcd:
    container_name: etcd
    image: quay.io/cybozu/etcd:3.3
    user: "${UID}:${GID}"
    volumes:
      - ./etcd-data:/data/etcd
      - ./etcd.conf.yml:/etc/etcd/etcd.conf.yml
      - ./bin:/host
      - ./etcd-entrypoint.sh:/entrypoint.sh
    ports:
      - "2379:2379"
      - "2380:2380"
    restart: always
    entrypoint:
      - /entrypoint.sh
