apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-dns
  namespace: kube-system
  annotations:
    cke.cybozu.com/revision: "1"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-dns
  namespace: kube-system
  annotations:
    cke.cybozu.com/revision: "1"
