name: sonobuoy
on:
  workflow_dispatch:
env:
  go-version: 1.17
jobs:
  sonobuoy:
    name: Run sonobuoy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Set up Cloud SDK for cke
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.NECO_TEST_PROJECT_ID }}
          service_account_key: ${{ secrets.NECO_TEST_SERVICE_ACCOUNT }}
          export_default_credentials: true
      - name: Set GCP instance name
        run: echo "INSTANCE_NAME=cke-${{ matrix.suite }}-${{ github.run_number }}-$(TZ=Asia/Tokyo date +%H%M%S)" >> $GITHUB_ENV
      - name: Run sonobuoy
        run: ./bin/run-sonobuoy.sh
        timeout-minutes: 240
      - name: Check failures
        run: |
          grep -F 'no tests failed for plugin "e2e" in tarball' /tmp/e2e-check.log
