name: sonobuoy
on:
  workflow_dispatch:
jobs:
  sonobuoy:
    name: Run sonobuoy
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.NECO_TEST_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v2
      - name: Set GCP instance name
        run: echo "INSTANCE_NAME=cke-${{ matrix.suite }}-${{ github.run_number }}-$(TZ=Asia/Tokyo date +%H%M%S)" >> $GITHUB_ENV
      - name: Run sonobuoy
        run: ./bin/run-sonobuoy.sh
        timeout-minutes: 240
      - name: Check failures
        run: |
          grep -F 'no tests failed for plugin "e2e" in tarball' /tmp/e2e-check.log
      - name: Upload sonobuoy test result
        uses: actions/upload-artifact@v4
        with:
          name: sonobuoy-test
          path: /tmp/sonobuoy.tar.gz
          retention-days: 1
        if: always()
